FROM rust:1.46 as builder

RUN rustup target install aarch64-unknown-linux-musl
WORKDIR /tmp/workdir
COPY ./nsm-lib nsm-lib
COPY ./nsm-io nsm-io
COPY ./nsm-driver nsm-driver
COPY ./nsm-test nsm-test
COPY ./Cargo.toml Cargo.toml
## command-executer binary is required from aws-nitro-enclaves-cli repository
COPY ./command-executer/command_executer_docker_dir/command-executer command-executer
RUN cargo build
RUN cargo install --path nsm-test
RUN strip /usr/local/cargo/bin/nsm-check
RUN cd nsm-test/ && make

FROM public.ecr.aws/debian/debian:buster-slim as nsm-check
COPY --from=builder /usr/local/cargo/bin/nsm-check nsm-check
COPY --from=builder /tmp/workdir/command-executer command-executer
ENTRYPOINT ["/bin/bash", "-l", "-c"]
CMD ./command-executer listen --port 5005

FROM public.ecr.aws/debian/debian:buster-slim as nsm-test-cpp
RUN apt-get update
RUN apt-get install -y libssl-dev
COPY --from=builder /tmp/workdir/nsm-test   nsm-test
COPY --from=builder /tmp/workdir/command-executer command-executer
ENTRYPOINT ["/bin/bash", "-l", "-c"]
CMD ./command-executer listen --port 5005

FROM public.ecr.aws/debian/debian:buster-slim as nsm-multithread
COPY --from=builder /usr/local/cargo/bin/nsm-multithread nsm-multithread
COPY --from=builder /tmp/workdir/command-executer command-executer
ENTRYPOINT ["/bin/bash", "-l", "-c"]
CMD ./nsm-multithread
